name: party-planner
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

env:
  DB_NAME: party
  DB_USERNAME: partyplanner
  DB_PASSWORD: PartyPlanner!!

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: ssh to pull latest version
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd party-planner
          git pull frankie frankie
          npm install
          forever restart -c 'npm start' .
        host: partyplanner.frankieyip.world
        user: ubuntu
        key: ${{secrets.SSH_PRIVATE_KEY}}